# This is the top-level variable file that will be used for the FlexPod setup. It is setup in this case to have FC
# SAN boot with FC-NVMe and NFS storage protocols. Notice that the configure_iSCSI variable is set to false, meaning FC
# boot is configured. We are also assuming that FC-NVMe will only be used with FC boot and that NVMe-TCP will only be
# used with iSCSI boot. Also, all protocols can be set to 'true'. 
#
# Setting the following variables to anything but 'true' ('false' is suggested when not using 'true'), will cause the 
# protocol to not be configured.
configure_iscsi: 'false'
configure_nvme_tcp: 'false'  # Only set this to 'true' if configure_iscsi is set to 'true'

configure_fc: 'true'
configure_fc_nvme: 'true'   # Only set this to 'true' if configure_fc is set to 'true'  

configure_nfs: 'true'       # In FlexPod, nfs is always used unless you have an All SAN Array (ASA)
#
# Update the the following lines to setup NTP Server(s)
# Note that the Nexus switches can be used to distribute NTP within the FlexPod and keep most NTP queries within the pod. When Nexus NTP distribution is setup, all L3 interfaces on the switch can be queried as NTP servers, including the IPs on the mgmt0 ports. In this FlexPod setup, the mgmt0 ports in the OOB-MGMT VLAN are setup along with SVI interfaces in the IB-MGMT VLAN to allow physical devices, ESXi hosts, and VMs to query NTP within the VLAN and within the pod.
use_nexus_ntp_distribution: 'true' # If not using Nexus NTP distribution, set this to 'false'.
global_NTP_servers:   # These are the Global NTP servers from outside the FlexPod (normally 2 or more).
  - "10.102.0.251"
  - "10.102.0.252"
ntp_servers:  # The first two entries here are the Nexus mgmt0 OOB-MGMT IPs. The third entry is a global NTP server because NetApp ONTAP requires three NTP servers. If not using Nexus NTP distribution, set all three of these still needed values to global NTP servers.
  - ip_address: "10.102.0.3"
  - ip_address: "10.102.0.4"
  - ip_address: "10.102.0.254"
ib_mgmt_ntp_servers:   # Assigned IB-MGMT NTP Addresses to be used by ESXi hosts and VMs. If not using Nexus NTP distribution, set these still needed values to global NTP servers.
  - ip_address: "10.102.1.3"
  - ip_address: "10.102.1.4"

# Update the the following lines to setup DNS Server(s)
# Note: The Nexus and MDS scripts assume exactly 2 DNS servers.
dns_servers:
  - ip_address: "10.102.1.151"
  - ip_address: "10.1.102.1521"

# DNS Domain Name
dns_domain_name: "flexpodb4.cisco.com"

# Update the the following line to setup Timezone
time_zone: 'America/New_York'

# ESXi Host Names - Separated by either FC or iSCSI. If not using the protocol, comment out the list entries.
# These host names and identifiers will be used for NetApp LUN and igroup names and Cisco MDS Device Alias names 
# and zone entries.
# They can also be assigned as UCS Profile names.

fc_esxi_hosts:
  - hostname: "aa02-esxi-01"
    fcp_a_wwpn: "20:00:00:25:B5:A2:0A:00"
    fcp_b_wwpn: "20:00:00:25:B5:A2:0B:00"
    fc_nvme_a_wwpn: "20:00:00:25:B5:A2:0A:01"
    fc_nvme_b_wwpn: "20:00:00:25:B5:A2:0B:01"
    nvme_nqn: "nqn.2014-08.com.cisco.flexpod:nvme:aa02-esxi-01"
  - hostname: "aa02-esxi-02"
    fcp_a_wwpn: "20:00:00:25:B5:A2:0A:02"
    fcp_b_wwpn: "20:00:00:25:B5:A2:0B:02"
    fc_nvme_a_wwpn: "20:00:00:25:B5:A2:0A:03"
    fc_nvme_b_wwpn: "20:00:00:25:B5:A2:0B:03"
    nvme_nqn: "nqn.2014-08.com.cisco.flexpod:nvme:aa02-esxi-02"
  - hostname: "aa02-esxi-03"
    fcp_a_wwpn: "20:00:00:25:B5:A2:0A:04"
    fcp_b_wwpn: "20:00:00:25:B5:A2:0B:04"
    fc_nvme_a_wwpn: "20:00:00:25:B5:A2:0A:05"
    fc_nvme_b_wwpn: "20:00:00:25:B5:A2:0B:05"
    nvme_nqn: "nqn.2014-08.com.cisco.flexpod:nvme:aa02-esxi-03"

iscsi_esxi_hosts:
  - hostname: "aa02-esxi-04"
    iscsi_iqn: "iqn.2010-11.com.flexpod:aa02-ucshost:1"
    nvme_nqn: "nqn.2014-08.com.cisco.flexpod:nvme:aa02-esxi-04"
  - hostname: "aa02-esxi-05"
    iscsi_iqn: "iqn.2010-11.com.flexpod:aa02-ucshost:2"
    nvme_nqn: "nqn.2014-08.com.cisco.flexpod:nvme:aa02-esxi-05"
  - hostname: "aa02-esxi-06"
    iscsi_iqn: "iqn.2010-11.com.flexpod:aa02-ucshost:3"
    nvme_nqn: "nqn.2014-08.com.cisco.flexpod:nvme:aa02-esxi-05"

# Storage SAN Identifiers
#
# Storage FCP WWPNs (capture from storage system)
#
fcp_lif_01a: '20:01:d0:39:ea:17:12:9b'
fcp_lif_02a: '20:03:d0:39:ea:17:12:9b'
fcp_lif_01b: '20:02:d0:39:ea:17:12:9b'
fcp_lif_02b: '20:04:d0:39:ea:17:12:9b'
#
# Storage FC-NVMe WWPNs (capture from storage system)
#
fc_nvme_lif_01a: '20:06:d0:39:ea:17:12:9b'
fc_nvme_lif_02a: '20:08:d0:39:ea:17:12:9b'
fc_nvme_lif_01b: '20:07:d0:39:ea:17:12:9b'
fc_nvme_lif_02b: '20:09:d0:39:ea:17:12:9b'
#
# Storage iSCSI Target Interfaces
#
iscsi_lif_01a: '192.168.10.31'
iscsi_lif_01b: '192.168.20.31'
iscsi_lif_02a: '192.168.10.32'
iscsi_lif_02b: '192.168.20.32'
#
# Storage iSCSI Target IQN
#
storage_iscsi_IQN: 'iqn.1992-08.com.netapp:sn.b04bca2ff83a11eea2aad039ea166b8c:vs.3'
#
# This is the list of all the VLANs that will be defined on Nexus, Storage, UCS, and VMware
# VLAN Names are adjustable and can be modified in here
# Comment out any VLANs that are not used here and below (iSCSI and NVMe-TCP)
#
native_vlan_name: 'Native-Vlan' # Native VLAN
native_vlan_id: 2
oob_vlan_name: 'OOB-MGMT' # Out of Band Mgmt VLAN
oob_vlan_id: 1020
ib_vlan_name: 'IB-MGMT' # IN BAND Management VLAN
ib_vlan_id: 1021
vm_vlan_name: 'VM-Traffic' # VLAN to carry VM traffic on VDS
vm_vlan_id: 1022
vmotion_vlan_name: 'vMotion' # vMotion VLAN
vmotion_vlan_id: 3000
nfs_vlan_name: 'Infra-NFS' # NFS Traffic between ESXi and Storage
nfs_vlan_id: 3050
iscsiA_vlan_name: 'Infra-iSCSI-A' # iSCSI-A VLAN (if needed)
iscsiA_vlan_id: 3010
iscsiB_vlan_name: 'Infra-iSCSI-B' # iSCSI-B VLAN (if needed)
iscsiB_vlan_id: 3020
nvme_tcpA_vlan_name: 'Infra-NVMe-TCP-A' # NVMe-TCP-A VLAN (if needed)
nvme_tcpA_vlan_id: 3030
nvme_tcpB_vlan_name: 'Infra-NVMe-TCP-B' # NVMe-TCP-B VLAN (if needed)
nvme_tcpB_vlan_id: 3040
#
# lan_state should be set to 'present' to configure the objects
# In future, this parameter will be used for deleting the configuration
#
lan_state : 'present'
#
# VLAN Lists - Comment out or remove any VLANs not being used.
#
# The ib_mgmt_vlan_list contains one entry, the IB-MGMT VLAN.
#
ib_mgmt_vlan_list:
  - name: "{{ ib_vlan_name }}"
    id: "{{ ib_vlan_id }}"
    native: 'no'
    state: "{{ lan_state }}"
#
# The storage_vlan_list contains VLANs that are configured on the storage controllers.
# These VLANs are also configured in the UCS and in the Nexus switches. This list has
# two extra fields, storage_protocol, and fabric. Do not remove these extra fields.
#
storage_vlan_list:
  - name: "{{ nfs_vlan_name }}"
    id: "{{ nfs_vlan_id }}"
    native: 'no'
    storage_protocol: NFS
    state: "{{lan_state}}"
    # ISCSI A and B VLANs should be deleted or commented out for Fiber-Channel-Only deployments
#  - name: "{{ iscsiA_vlan_name }}"
#    id: "{{ iscsiA_vlan_id }}"
#    native: 'no'
#    storage_protocol: iSCSI
#    fabric: A
#    state: "{{lan_state}}"
#  - name: "{{ iscsiB_vlan_name }}"
#    id: "{{ iscsiB_vlan_id }}"
#    native: 'no'
#    storage_protocol: iSCSI
#    fabric: B
#    state: "{{lan_state}}"
#  - name: "{{ nvme_tcpA_vlan_name }}"
#    id: "{{ nvme_tcpA_vlan_id }}"
#    native: 'no'
#    storage_protocol: NVMe
#    fabric: A
#    state: "{{lan_state}}"
#  - name: "{{ nvme_tcpB_vlan_name }}"
#    id: "{{ nvme_tcpB_vlan_id }}"
#    native: 'no'
#    storage_protocol: NVMe
#    fabric: B
#    state: "{{lan_state}}"

# The remaining_vlan_list contains all vlans that are not configured on storage,
# but are configured in Nexus and UCS.
#
remaining_vlan_list:
  - name: "{{ native_vlan_name }}"
    id: "{{ native_vlan_id }}"
    native: 'yes'
    state: "{{lan_state}}"
  - name: "{{ oob_vlan_name }}"
    id: "{{ oob_vlan_id }}"
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vm_vlan_name }}"
    id: "{{ vm_vlan_id }}"
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vmotion_vlan_name }}"
    id: "{{ vmotion_vlan_id }}"
    native: 'no'
    state: "{{lan_state}}"

# VLANs definitions below will be used to setup trunk ports on Nexus Switches
# all_vlans_list: for vpc_peer_link and UCS FI trunk ports
# These VLANs must be same or a subset of the vlan_list abovea
# Comment out or remove any VLANs that are not used (iSCSI and NVMe-TCP)
# In future, these values will be auto-generated
#
all_vlans_list: "{{ oob_vlan_id }},{{ ib_vlan_id }},{{ vm_vlan_id }},{{ nfs_vlan_id }},{{ vmotion_vlan_id }}" #,{{ iscsiA_vlan_id }},{{ iscsiB_vlan_id }},{{ nvme_tcpA_vlan_id }},{{ nvme_tcpB_vlan_id }}"
# storage_vlans_list: for storage uplink trunk ports
storage_vlans_list: "{{ ib_vlan_id }},{{ nfs_vlan_id }}" #,{{ iscsiA_vlan_id }},{{ iscsiB_vlan_id }},{{ nvme_tcpA_vlan_id }},{{ nvme_tcpB_vlan_id }}"
# mgmt_vlans_list: for uplink/management switch trunk port
mgmt_vlans_list: "{{ oob_vlan_id }},{{ ib_vlan_id }},{{ vm_vlan_id }}"
#
# VLAN/Portgroup List with Pinning info for VMware Distributed Switch vDSO for vMotion and Tenant Data/Storage
vds0_vlan_list:
  - name: "{{ vm_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ vm_vlan_name }}"
    id: "{{ vm_vlan_id }}"
    active_uplinks: 
      - "Uplink 1"
      - "Uplink 2"
    standby_uplinks: []
  - name: "{{ vmotion_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ vmotion_vlan_name }}"
    id: "{{ vmotion_vlan_id }}"
    active_uplinks: "Uplink 2"
    standby_uplinks: "Uplink 1"
  - name: "{{ nfs_vlan_name }}" # In case you want to move Infra-NFS to vDS0.
    # portgroup name will be configured in VMware
    portgroup_name: "{{ nfs_vlan_name }}"
    id: "{{ nfs_vlan_id }}"
    active_uplinks:
      - "Uplink 1"
      - "Uplink 2"
    standby_uplinks: []
#
# VLAN/Portgroup List with Pinning info for VMware Distributed Switch iSCSI-NVMe-TCP-vDS for iSCSI and NVMe Storage
iscsi_nvme_tcp_vds_vlan_list:
  - name: "{{ iscsiA_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ iscsiA_vlan_name }}"
    id: '0'  # iSCSI VLAN A is set as native for this vNIC
    active_uplinks:
      - "Uplink 1"
    standby_uplinks: []
  - name: "{{ iscsiB_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ iscsiB_vlan_name }}"
    id: '0'  # iSCSI VLAN B is set as native for this vNIC
    active_uplinks:
      - "Uplink 2"
    standby_uplinks: []
  - name: "{{ nvme_tcpA_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ nvme_tcpA_vlan_name }}"
    id: "{{ nvme_tcpA_vlan_id }}"
    active_uplinks:
      - "Uplink 1"
    standby_uplinks: []
  - name: "{{ nvme_tcpB_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ nvme_tcpB_vlan_name }}"
    id: "{{ nvme_tcpB_vlan_id }}"
    active_uplinks:
      - "Uplink 2"
    standby_uplinks: []

nfs_portgroup: "VMKernel-Infra-NFS"
esxi_nfs_vlan: "{{ nfs_vlan_id }}"
#
oob_mgmt_portgroup: "OOB-MGMT Network"
oob_mgmt_vlan: "{{ oob_vlan_id }}"
#
#VSAN Parameters
#
vsan_A_name: 'FlexPod-Fabric-A'
vsan_A_id: 101
vsan_A_fcoe_vlan: 101
#
vsan_B_name: 'FlexPod-Fabric-B'
vsan_B_id: 102
vsan_B_fcoe_vlan: 102
#
# VMware Configurations
# provide the user names and passwords to connect to the ESXi servers
# and VMware vCenter
#
esxi_username: root
esxi_password: "{{ ansible_ssh_pass }}"
#
vcenter_dc: FlexPod-DC
vcenter_cluster: FlexPod-Management
#
vcenter_hostname: "10.102.1.100"
# e.g. vcenter_hostname: 10.50.160.100
vcenter_username: "administrator@vsphere.local"
# e.g. vcenter_username: administrator@vsphere.local
vcenter_password: "{{ password_2 }}"
# e.g. vcenter_password: "{{ password_2 }}"
#
# DVS Parameters
#
dvs_name: "vDS0"
iscsi_nvme_tcp_dvs_name: "iSCSI-NVMe-TCP-vDS" # Change to "iSCSI-vDS" if not using NVMe-TCP
dv_version: "8.0.0" # This parameter is not used. The latest DVS version on the vCenter will be used.
dv_uplink: "2"
dv_protocol: "lldp"
dv_operation: "both"
