---
  # This Task enables Nexus 9K NTP Distribution for the FlexPod
  
  - name: Set NTP Servers
    cisco.nxos.nxos_ntp_global:
      config:
        servers:
          - server: "{{ item }}"
            vrf: management
    with_items: "{{ global_NTP_servers }}"
  - name: Set partner switch as peer
    cisco.nxos.nxos_ntp_global:
      config:
        peers:
          - peer: "{{ vpc_destination }}"
            vrf: management
    when: use_nexus_ntp_distribution == 'true'
  - name: Set NTP Distribution Options
    cisco.nxos.nxos_ntp_global:
      config:
        master: 
          stratum: '3'
    when: use_nexus_ntp_distribution == 'true'
  - name: Create NTP Distribution Interface
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: Vlan"{{ ntp_distribution_vlan }}"
        ipv4:
        - address: "{{ IB_MGMT_ntp_dist_IP }}"
    when: use_nexus_ntp_distribution == 'true'
  - name: Enable NTP Distribution Interface
    cisco.nxos.nxos_interfaces:
      config:
      - name: Vlan"{{ ntp_distribution_vlan }}"
        enabled: true
    when: use_nexus_ntp_distribution == 'true'
